name: cabal:build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check-format:
    if: "!contains(github.event.pull_request.labels.*.name, 'ignore-server-format-checks')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ormolu
        uses: haskell-actions/run-ormolu@v16
        with:
          mode: check
          pattern: "**/*.hs"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: "9.10.3"
          cabal-version: "3.12"

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-

      - name: Build
        run: cabal build all
